; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-mini]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
board_build.partitions = partitions_4mb.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 3145728
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder
build_src_filter =
  +<*>
  -<test_main.cpp>
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=3
  -D FCU_SENSITIVE_PIN_SAFE_BOOT_MS=10000U
  -D FCU_PIN_NRF_MOSI=4
  -D FCU_PIN_NRF_MISO=5
  -D FCU_PIN_NRF_SCK=6
  -D FCU_PIN_CTRL_CSN=7
  -D FCU_PIN_CTRL_CE=15
  -D FCU_PIN_CTRL_IRQ=16
  -D FCU_PIN_TELM_CSN=8
  -D FCU_PIN_TELM_CE=21
  -D FCU_PIN_TELM_IRQ=38
  -D FCU_ENABLE_TELEMETRY_RADIO=0
  -D FCU_PIN_NRF_RX_OK_LED=47
  -D FCU_PIN_NRF_TX_OK_LED=48
lib_deps =
  https://github.com/AhmadAbdel-R/easy-esc-esp32.git#23b8081a96c9aaeff0fac725d5ea4050eb2ab688
  nrf24/RF24 @ ^1.4.11
  adafruit/Adafruit ICM20X @ ^2.0.7
  adafruit/Adafruit VL53L1X @ ^3.1.2
  ; adafruit/Adafruit BMP280 Library @ ^2.6.8
  ; https://github.com/adafruit/Adafruit_ICM20X.git

[env:test]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D FCU_PIN_NRF_MOSI=4
  -D FCU_PIN_NRF_MISO=5
  -D FCU_PIN_NRF_SCK=6
  -D FCU_PIN_CTRL_CSN=7
  -D FCU_PIN_CTRL_CE=15
  -D FCU_PIN_CTRL_IRQ=16
  -D FCU_PIN_TELM_CSN=8
  -D FCU_PIN_TELM_CE=21
  -D FCU_PIN_TELM_IRQ=38
  -D FCU_ENABLE_TELEMETRY_RADIO=1
  -D FCU_PIN_NRF_RX_OK_LED=47
  -D FCU_PIN_NRF_TX_OK_LED=48
  -D FCU_RADIO_SPI_HZ=10000000UL
  -D FCU_IMU_SPI_HZ=7000000UL
build_src_filter =
  -<*>
  +<test_main.cpp>
lib_deps =
  nrf24/RF24 @ ^1.4.11
  adafruit/Adafruit ICM20X @ ^2.0.7
  adafruit/Adafruit VL53L1X @ ^3.1.2
